---
- apt: update_cache=yes
  tags:
    - exakat

# Common configurations to be run on all hosts
- name: clean exakat
  file: path=/home/vagrant/exakat.phar state=absent
  tags:
    - exakat

- name: clean exakat old config
  file: path=/home/vagrant/config state=absent
  tags:
    - exakat

- name: download exakat
  get_url: url=http://dist.exakat.io/versions/index.php?file=latest dest=/home/vagrant/exakat.phar mode=0777
  tags:
    - exakat

- name: control over paths
  file: path=/home/vagrant/ recurse=yes owner=vagrant
  tags:
    - exakat

- name: test exakat
  shell: php /home/vagrant/exakat.phar doctor
  tags:
    - exakat

- name: test exakat-PHP 7.2-dev (aka master)
  lineinfile: dest=/home/vagrant/config/exakat.ini regexp="php          = "= line="php          = /usr/local/bin/php72"
  tags:
    - exakat

- name: test exakat-PHP 7.1
  lineinfile: dest=/home/vagrant/config/exakat.ini regexp=";php71        = /path/to/php71"= line="php71        = /usr/local/bin/php71"
  tags:
    - exakat

- name: test exakat-PHP 7.0
  lineinfile: dest=/home/vagrant/config/exakat.ini regexp=";php70        = /path/to/php70"= line="php70        = /usr/local/bin/php70"
  tags:
    - exakat

- name: test exakat-PHP 5.6
  lineinfile: dest=/home/vagrant/config/exakat.ini regexp=";php56        = /path/to/php56"= line="php56        = /usr/local/bin/php56"
  tags:
    - exakat

- name: test exakat-PHP 5.5
  lineinfile: dest=/home/vagrant/config/exakat.ini regexp=";php55        = /path/to/php55"= line="php55        = /usr/local/bin/php55"
  tags:
    - exakat

- name: test exakat-PHP 5.6
  lineinfile: dest=/home/vagrant/config/exakat.ini regexp=";php54        = /path/to/php56"= line="php54        = /usr/local/bin/php54"
  tags:
    - exakat


## Still needs to modify the config/config.ini file
